### ISSUE TITLE
Declarations in extensions cannot override yet

### ISSUE THREAD

**Issue by Decybel07** [PiXeL16/IBLocalizable#10]
I can't build my project because you have a bug

<img width="719" alt="zrzut ekranu 2017-12-23 o 17 24 34" src="https://user-images.githubusercontent.com/15947101/34321050-2ed3ea68-e806-11e7-977e-8acc0ec7dcc7.png">

Can you solve it or help me with this bug?

**Comment by yesidi** [comment]
I have this too, how to solve it?

**Comment by yesidi** [comment]
I sloved this issue: you must using swift 4 branch to import to your xcode.

**Comment by PiXeL16** [comment]
I just merged Swift 4 compatibility to Master
