### ISSUE TITLE
Overriding non-open var outside its defining module

### ISSUE THREAD

**Issue by munirwanis** [PiXeL16/IBLocalizable#15]
I can't override `localizableProperty` because it gives me that error:

![screen shot 2018-04-10 at 16 06 29](https://user-images.githubusercontent.com/8562684/38578217-aaa05762-3cd9-11e8-872a-3e1302a6bea2.png)

**Comment by PiXeL16** [comment]
Is this in your class or in the library? Have you tried declaring it as open?

**Comment by munirwanis** [comment]
In my class, just like the example on your README. Tried open and it didn't work.

**Comment by PiXeL16** [comment]
The localizableProperty probably has to be declared as `open` in the library so you can override it. It probably broke recently in one of the Swift4 migrations. Do you want a submit a PR with the fix?

**Comment by munirwanis** [comment]
I would love to, but right now I can't test it.
