### ISSUE TITLE
Type 'UIControl' has no member 'State' build error

### ISSUE THREAD

**Issue by devferrazZz** [PiXeL16/IBLocalizable#18]
Based on this [answer](https://stackoverflow.com/questions/45662507/whats-the-difference-between-uicontrolstate-and-uicontrolstate-normal-when?answertab=active#tab-top) on SO I would like to suggest to update the [LocalizableButton.swift](https://github.com/PiXeL16/IBLocalizable/blob/master/IBLocalizable/Views/LocalizableButton.swift#L19).

`self.setTitle(newValue, for: UIControl.State())` to `self.setTitle(newValue, for: .normal)`

I had a build error _Type 'UIControl' has no member 'State'_ on Xcode 9.4.1, Swift 4.1 and had to change it to make it work

**Comment by PiXeL16** [comment]
Sounds interesting, please send a PR with your proposal

**Comment by devferrazZz** [comment]
Since the PR was merged I'm closing this. Thanks!
