### ISSUE TITLE
Change Language by manually

### ISSUE THREAD

**Issue by syedrazackimran** [PiXeL16/IBLocalizable#7]
Hi, 
 i tried to implement your lib. but i have serval doubts, how i can change lng by manually . 
do have any method to pass lng short to access  Localizable.string file.

**Comment by PiXeL16** [comment]
Hi @syedrazackimran. Not sure what you mean. The language is generally chosen automatically by the OS based on what language the device is in. It also depends on the localizable.strings that you provide in your app.

**Comment by PiXeL16** [comment]
Closing due to lack of response. Please open again if you encounter any other issues.
Thanks!

**Comment by syedrazackimran** [comment]
Hi hello,

I Mean in my application have Chinese, English and Spanish language. a user can able to choose they're preferred language in setting UI. if user change language how to change language manually.
