### ISSUE TITLE
Swift 4 issue: Declarations in extensions cannot override yet

### ISSUE THREAD

**Issue by tdimeco** [PiXeL16/IBLocalizable#9]
Hey!

There is an issue with Swift 4 and extension overrides: `Declarations in extensions cannot override yet` (see attached picture).

<img width="1407" alt="error" src="https://user-images.githubusercontent.com/3112087/30654739-14c9e288-9e2f-11e7-94f9-28814a13ae4c.png">

This is a non-blocking issue as it continue to work with Xcode 9 and the Swift 3 mode we can set manually, and for now the issue is related to Cocoapods.

Have a good day!
Best regards.

Thomas

**Comment by PiXeL16** [comment]
@tdimeco There is a Swift4 branch in the project that you should fix this issue.
